// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAs-NQVKV7ZeJ92nefmq1HEvkgRFn0i5Jc',
//     appId: '1:315657446948:android:3f6cae51d979bdc3419ab1',
//     messagingSenderId: '315657446948',
//     projectId: 'fir-demo1-34375',
//     storageBucket: 'fir-demo1-34375.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDkwAX3YyxSkjPP90lxJKV9FE9Hupe_QNQ',
//     appId: '1:315657446948:ios:c6621e966131eac9419ab1',
//     messagingSenderId: '315657446948',
//     projectId: 'fir-demo1-34375',
//     storageBucket: 'fir-demo1-34375.appspot.com',
//     androidClientId: '315657446948-52njfm7bj982ov5cuorbs2snc8tt2uot.apps.googleusercontent.com',
//     iosClientId: '315657446948-aielqr452ngft771bjls36uogs5hvek9.apps.googleusercontent.com',
//     iosBundleId: 'com.example.gaydatingapp',
//   );
// }
